/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./src/components/navigation/BackButton.vue')['default']
    BottomNavigation: typeof import('./src/components/navigation/BottomNavigation.vue')['default']
    DataReloadButton: typeof import('./src/components/DataReloadButton.vue')['default']
    EventCard: typeof import('./src/components/problemstoffmobil/EventCard.vue')['default']
    HeadlineBar: typeof import('./src/components/HeadlineBar.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    LocationMap: typeof import('./src/components/map/LocationMap.vue')['default']
    LocationMetricCard: typeof import('./src/components/metric/LocationMetricCard.vue')['default']
    MapNavigationCard: typeof import('./src/components/map/MapNavigationCard.vue')['default']
    MarkdownWrapper: typeof import('./src/components/MarkdownWrapper.vue')['default']
    MaterialCallToActionButton: typeof import('./src/components/material/MaterialCallToActionButton.vue')['default']
    MaterialMetricCard: typeof import('./src/components/metric/MaterialMetricCard.vue')['default']
    MaterialSearchbar: typeof import('./src/components/searchbar/MaterialSearchbar.vue')['default']
    MaterialTargetDetail: typeof import('./src/components/material/MaterialTargetDetail.vue')['default']
    MunicipalityFilter: typeof import('./src/components/problemstoffmobil/MunicipalityFilter.vue')['default']
    PartnerCard: typeof import('./src/components/partner/PartnerCard.vue')['default']
    PartnerCarousel: typeof import('./src/components/partner/PartnerCarousel.vue')['default']
    PartnerMetricCard: typeof import('./src/components/metric/PartnerMetricCard.vue')['default']
    PressCard: typeof import('./src/components/press/PressCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareButton: typeof import('./src/components/navigation/ShareButton.vue')['default']
    TargetChip: typeof import('./src/components/target/TargetChip.vue')['default']
    TargetImage: typeof import('./src/components/target/TargetImage.vue')['default']
    TipCard: typeof import('./src/components/tips/TipCard.vue')['default']
    TippMetricCard: typeof import('./src/components/metric/TippMetricCard.vue')['default']
  }
}
