name: bun CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: bun install --frozen-lockfile
    - run: bun build --if-present